"""Auto-generated by cad_ai/scripts/cad_ai/ir_compile.py.
Do not edit by hand; regenerate from the CAD-IR.
"""
from __future__ import annotations

from build123d import (
    BuildPart, BuildSketch, Circle, Locations, Mode, Part, Plane,
    Rectangle, extrude, fillet, chamfer, RegularPolygon,
)

params = {'base_height': 15.0, 'stem_height': 350.0, 'shade_segment_height': 30.0, 'base_radius': 60.0, 'stem_radius': 9.0, 'shade_top_radius': 15.0, 'shade_mid_radius': 30.0, 'shade_bot_radius': 50.0, 'shade_top_z': 365.0, 'shade_mid_z': 395.0, 'shade_bot_z': 425.0}


# --- main build ---
with BuildPart() as bp:
    with BuildSketch(Plane.XY):
        with Locations((0, 0)):
            Circle(params['base_radius'] / 2)
    extrude(amount=params['base_height'])
    with BuildSketch(Plane.XY.offset(params['base_height'])):
        with Locations((0, 0)):
            Circle(params['stem_radius'] / 2)
    extrude(amount=params['stem_height'])
    with BuildSketch(Plane.XY.offset(params['shade_top_z'])):
        with Locations((0, 0)):
            Circle(params['shade_top_radius'] / 2)
    extrude(amount=params['shade_segment_height'])
    with BuildSketch(Plane.XY.offset(params['shade_mid_z'])):
        with Locations((0, 0)):
            Circle(params['shade_mid_radius'] / 2)
    extrude(amount=params['shade_segment_height'])
    with BuildSketch(Plane.XY.offset(params['shade_bot_z'])):
        with Locations((0, 0)):
            Circle(params['shade_bot_radius'] / 2)
    extrude(amount=params['shade_segment_height'])

base = bp.part
body = base
body.label = 'lamp_minimal'


def gen_step():
    return body
